version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:14.19

jobs:
  test:
    <<: *defaults
    environment:
      MOCHA_REPORTER: mocha-junit-reporter
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Install dependecies
          command: npm install
      # - run:
      #     name: Run tests
      #     command: npm run test
      - store_test_results:
          path: ~/repo/results
      - store_artifacts:
          path: ~/repo/results
      - store_test_results:
          path: ~/repo/coverage
      - store_artifacts:
          path: ~/repo/coverage
  publish-default:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build 'default'
          command: ./scripts/build_default.sh
      - run:
          name: Create .npmrc file
          command: cd build && echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish package
          command: cd build && npm publish --access public
  publish-node:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build 'node'
          command: ./scripts/build_node.sh
      - run:
          name: Create .npmrc file
          command: cd build && echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish package
          command: cd build && npm publish --access public

workflows:
  version: 2
  publish:
    jobs:
      - test
      - approve_publish:
          type: approval
          requires:
            - test
      - publish-default:
          requires:
            - approve_publish
      - publish-node:
          requires:
            - publish-default
